name: flutterappversion
description: read and write versionName and versionCode
publish_to: "none"
version: 1.0.0

environment:
  flutter: ">=3.10.0"
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  yaml_modify: ^1.0.1
